import IemDetail from "../../components/contents/IemDetail";
import Head from 'next/head'

export async function getStaticPaths() {

    const result = await fetch('http://localhost:3000/api/iems/props').then(res => res.json());

    const paths = result.data.map(iem => ({
        params: {id: iem._id}
    }));

    return {paths, fallback: false}
}

export async function getStaticProps({params}) {

    const result = await fetch(`http://localhost:3000/api/iems/${params.id}`).then(res => res.json());
    return {props: {
        iem: result
    }}
}

const Detail = ({iem}) => {
    return (
        <>
            <Head>
                <title>{iem.data?.model}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="https://crinacle.com/wp-content/uploads/2020/02/crinaclogo.png" />
            </Head>
            <IemDetail iem={iem} />
        </>
     );
}
 
export default Detail;