import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Info from '../../components/contents/Info'
import DarkMode from '../../components/DarkMode'
import IemRank from '../../components/contents/IemRank'
import Navbar from '../../components/Navbar'

export async function getServerSideProps({query}) {
    const result = await fetch(`http://localhost:3000/api/iems?keyword=${query.keyword}&limit=${query.limit}&offset=${query.offset}`).then(res => res.json());
    const sponsors = await fetch('http://localhost:3000/api/sponsors').then(res => res.json())

    return {
      props: {
        iems: result,
        sponsors
      }
    }
  } 

export default function Home({iems, sponsors}) {


  return (
    <div className='dark:bg-dark'>
      <Head>
        <title>Crinacle's IEMs Ranking List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://crinacle.com/wp-content/uploads/2020/02/crinaclogo.png" />
      </Head>

      <Navbar />

      <DarkMode />

      <main className={styles.main}>
        <Info sponsors={sponsors} />
        <IemRank iems={iems} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
